{
 "title": "Kubernetes Monitoring Overview",
 "description": "Dashboard for Kubernetes cluster with Prometheus.",
 "tags": [
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   { "name": "Node", "query": { "query": "label_values(node)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "application",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\"},container)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Internet   health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Internet Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "internet_connectivity_status{}" }
   ]
  },
  {
   "title": "DNS Error Rate ",
   "type": "stat",
   "description": "Rate of DNS failures in 5 minutes intervals",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(dns_errors_total[$__range])\n/\n(\n  increase(dns_success_total[$__range]) +\n  increase(dns_errors_total[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_rx_bps{interface=\"enp1s0\"} / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_tx_bps{interface=\"enp1s0\"} / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Median Latency",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(increase(internet_rtt_seconds_bucket[15m])) by (le)\n) * 1000"
    }
   ]
  },
  {
   "title": "Connection resets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(tcp_rst_errors_total[5m]) / clamp_min(rate(tcp_syn_total[5m]), 0.0001)) "
    }
   ]
  },
  {
   "title": "Link Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# More detailed severity mapping\n(\n  (internet_check_latency_seconds > bool 100) * 2\n) \n+ \n(\n  (increase(device_flaps_total[5m]) > bool 0) * 1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    (increase(device_flaps_total[$__rate_interval]) > bool 0) * 4\n  )\n  or\n  (\n    (histogram_quantile(\n        0.95,\n        sum(rate(internet_rtt_seconds_bucket[$__rate_interval])) by (le)\n     ) * 1000 > bool 300) * 3\n  )\n  or\n  (\n    (rate(dns_errors_total[$__rate_interval]) > bool 0) * 2\n  )\n  or\n  (\n    (rate(icmp_host_unreachable_total[$__rate_interval]) > bool 0) * 1\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local Network health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "LAN Devices",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(device_seen_by_mac{ip=~\"192.168.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(device_seen_by_mac{ip=~\"192.168.*\"}) - sum(device_seen_by_mac{ip=~\"192.168.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(device_seen_by_mac{ip=~\"192.168.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent flaps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(clamp_min(increase(device_flaps_total[$__range]), 0))"
    }
   ]
  },
  { "title": "Local Area Network  Faults", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "ICMP FAULTS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 13 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(increase(icmp_port_unreachable_total[$__range]), 0)",
     "legendFormat": "Port Unreachable"
    },
    {
     "expr": "clamp_min(increase(icmp_host_unreachable_total[$__range_s]), 0)",
     "legendFormat": "Host Unreachable"
    },
    {
     "expr": "clamp_min(increase(icmp_network_unreachable_total[$__range_s]), 0)",
     "legendFormat": "Network Unreachable"
    }
   ]
  },
  {
   "title": "Top ICMP Fault Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "clamp_min(increase(host_icmp_faults_total[$__range]), 0) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}